### PR TITLE
Laravel 5.5 support tweaks

### PR DESCRIPTION
**Pull request by tbergeron**
Thanks to @forelabs (https://github.com/fadion/Maneuver/issues/29#issuecomment-338747600), I implemented their findings and it seems to work across the board.

I'm glad it works again! 👍 

Please tell me if it looks okay, hope this helps!

### CODE REVIEW

**Comment by fadion** [comment]
Thanks @tbergeron for the PR. There's a little problem though, as it should be on the `l5` branch, not on `master`. I plan on making `master` for L5 and branching the current implementation to a `l4` branch, but for the time being we should live it as it is.

If it's too much of a burden for you, let me fix it within the following days.

**Comment by fadion** [comment]
Look, don't bother on changing the branch. I'll work during these days on fixing the `l5` branch, put it on master and tag it with a `v2` version. I'm sure most are using Laravel 5 anyway, but even if they don't, I'll leave the `v1` version for Laravel 4 users.

Is that ok?

**Comment by tbergeron** [comment]
Sounds great to me! I was okay with the branch change but that's even better if you can do this. I agree, all my projects are now on Laravel 5. I love this library, thanks a lot!

**Comment by forelabs** [comment]
I only used this little `hack` to get things working fast, after checking notes I found out that
`fire` simply has been renamed to `handle` in Laravel 5, but `fire` was left because of backwards compatibility. Now, this got removed. I would suggest to simply rename the methods instead of adding the alias one.

https://laravel.com/docs/5.5/upgrade

**Comment by tbergeron** [comment]
@fadion Any update about this yet? No hurry, just curious. I can still help if needed. Thanks!

**Comment by fadion** [comment]
@tbergeron Organised the repository with releases based on different Laravel versions, as it's generally the recommended approach. I'm closing the pull request, but please open an issue if you find something wrong. Sorry for the long delay, it's been a busy period.

**Pull request closed without merging**
